// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBB_9IfwamuXuDJ_7IrtoMr70uPm3_IW38',
    appId: '1:474737354940:web:18c2ff64b4e32a1d2948b9',
    messagingSenderId: '474737354940',
    projectId: 'krishism1',
    authDomain: 'krishism1.firebaseapp.com',
    storageBucket: 'krishism1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRPsoq-BOz_GTJEkp5iKwydka6TdtyzFY',
    appId: '1:474737354940:android:c7b7b4e193bb91d62948b9',
    messagingSenderId: '474737354940',
    projectId: 'krishism1',
    storageBucket: 'krishism1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTRIs9hXXZKSpWsFkhWS1iHRmmjCA0D_k',
    appId: '1:474737354940:ios:ba71e6b5b9441dd42948b9',
    messagingSenderId: '474737354940',
    projectId: 'krishism1',
    storageBucket: 'krishism1.firebasestorage.app',
    iosBundleId: 'com.example.farmingNew',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBTRIs9hXXZKSpWsFkhWS1iHRmmjCA0D_k',
    appId: '1:474737354940:ios:ba71e6b5b9441dd42948b9',
    messagingSenderId: '474737354940',
    projectId: 'krishism1',
    storageBucket: 'krishism1.firebasestorage.app',
    iosBundleId: 'com.example.farmingNew',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBB_9IfwamuXuDJ_7IrtoMr70uPm3_IW38',
    appId: '1:474737354940:web:bdc63ef162eae4a52948b9',
    messagingSenderId: '474737354940',
    projectId: 'krishism1',
    authDomain: 'krishism1.firebaseapp.com',
    storageBucket: 'krishism1.firebasestorage.app',
  );
}
